---@meta

---@class FAnimBlueprintGeneratedConstantData : FAnimBlueprintConstantData
---@field NameProperty_320 FName
---@field NameProperty_321 FName
---@field NameProperty_322 FName
---@field NameProperty_323 FName
---@field NameProperty_324 FName
---@field IntProperty_325 int32
---@field NameProperty_326 FName
---@field IntProperty_327 int32
---@field NameProperty_328 FName
---@field IntProperty_329 int32
---@field ArrayProperty_330 TArray<float>
---@field BlendProfile_331 UBlendProfile
---@field CurveFloat_332 UCurveFloat
---@field EnumProperty_333 EAlphaBlendOption
---@field EnumProperty_334 EBlendListTransitionType
---@field ArrayProperty_335 TArray<int32>
---@field EnumProperty_336 EAnimSyncMethod
---@field NameProperty_337 FName
---@field NameProperty_338 FName
---@field IntProperty_339 int32
---@field BoolProperty_340 boolean
---@field FloatProperty_341 float
---@field StructProperty_342 FInputScaleBiasClampConstants
---@field FloatProperty_343 float
---@field BoolProperty_344 boolean
---@field EnumProperty_345 EAnimSyncMethod
---@field ByteProperty_346 EAnimGroupRole::Type
---@field NameProperty_347 FName
---@field NameProperty_348 FName
---@field NameProperty_349 FName
---@field NameProperty_350 FName
---@field IntProperty_351 int32
---@field StructProperty_352 FAnimNodeFunctionRef
---@field AnimBlueprintExtension_PropertyAccess FAnimSubsystem_PropertyAccess
---@field AnimBlueprintExtension_Base FAnimSubsystem_Base
FAnimBlueprintGeneratedConstantData = {}



---@class FAnimBlueprintGeneratedMutableData : FAnimBlueprintMutableData
---@field AnimSequenceBase UAnimSequenceBase
---@field FloatProperty_0 float
---@field AnimSequenceBase_1 UAnimSequenceBase
---@field AnimSequenceBase_2 UAnimSequenceBase
---@field BlendSpace_3 UBlendSpace
---@field FloatProperty_4 float
---@field FloatProperty_5 float
---@field BlendSpace_6 UBlendSpace
---@field FloatProperty_7 float
---@field FloatProperty_8 float
---@field BlendSpace_9 UBlendSpace
---@field FloatProperty_10 float
---@field FloatProperty_11 float
---@field BlendSpace_12 UBlendSpace
---@field FloatProperty_13 float
---@field FloatProperty_14 float
---@field FloatProperty_15 float
---@field BlendSpace_16 UBlendSpace
---@field FloatProperty_17 float
---@field FloatProperty_18 float
---@field FloatProperty_19 float
---@field BoolProperty_20 boolean
---@field BoolProperty_21 boolean
---@field BoolProperty_22 boolean
---@field BlendSpace_23 UBlendSpace
---@field FloatProperty_24 float
---@field FloatProperty_25 float
---@field FloatProperty_26 float
---@field BoolProperty_27 boolean
---@field BlendSpace_28 UBlendSpace
---@field FloatProperty_29 float
---@field FloatProperty_30 float
---@field FloatProperty_31 float
---@field ArrayProperty_32 TArray<float>
---@field BoolProperty_33 boolean
---@field BlendSpace_34 UBlendSpace
---@field FloatProperty_35 float
---@field ArrayProperty_36 TArray<float>
---@field ByteProperty_37 uint8
---@field BlendSpace_38 UBlendSpace
---@field FloatProperty_39 float
---@field FloatProperty_40 float
---@field FloatProperty_41 float
---@field BlendSpace_42 UBlendSpace
---@field FloatProperty_43 float
---@field FloatProperty_44 float
---@field FloatProperty_45 float
---@field BlendSpace_46 UBlendSpace
---@field FloatProperty_47 float
---@field FloatProperty_48 float
---@field FloatProperty_49 float
---@field BlendSpace_50 UBlendSpace
---@field FloatProperty_51 float
---@field FloatProperty_52 float
---@field FloatProperty_53 float
---@field AnimSequenceBase_54 UAnimSequenceBase
FAnimBlueprintGeneratedMutableData = {}



---@class UAbp_HumanoidCS_Simple4Dir_C : UBUAnimHumanoidCS_Simple4Dir
---@field UberGraphFrame FPointerToUberGraphFrame
---@field __AnimBlueprintMutables FAnimBlueprintGeneratedMutableData
---@field AnimBlueprintExtension_PropertyAccess FAnimSubsystemInstance
---@field AnimBlueprintExtension_Base FAnimSubsystemInstance
---@field AnimGraphNode_Root FAnimNode_Root
---@field AnimGraphNode_TransitionResult_14 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_13 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_12 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_11 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_10 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_3 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_9 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_8 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_7 FAnimNode_StateResult
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_BlendSpacePlayer_11 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_6 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_10 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_5 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_9 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_GSOrientationWarping FAnimMode_GSOrientationWarping
---@field AnimGraphNode_BlendSpacePlayer_8 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_7 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByBool_4 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_3 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_2 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_6 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByBool_1 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_5 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByBool FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_4 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByEnum FAnimNode_BlendListByEnum
---@field AnimGraphNode_BlendSpacePlayer_3 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_2 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_1 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_2 FAnimNode_StateMachine
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_1 FAnimNode_StateMachine
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
---@field AnimGraphNode_LinkedInputPose FAnimNode_LinkedInputPose
UAbp_HumanoidCS_Simple4Dir_C = {}

---@param InPose FPoseLink
---@param AnimGraph FPoseLink
function UAbp_HumanoidCS_Simple4Dir_C:AnimGraph(InPose, AnimGraph) end
function UAbp_HumanoidCS_Simple4Dir_C:EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_BlendListByBool_1807C5B4455D7B071974BBB76625E78E() end
function UAbp_HumanoidCS_Simple4Dir_C:EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_BlendListByBool_71387B3C4302358A8D5D5887DDC22A19() end
function UAbp_HumanoidCS_Simple4Dir_C:EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_BlendListByBool_D35932C7404D125E33B0F2B6AB9D7E28() end
function UAbp_HumanoidCS_Simple4Dir_C:EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_BlendListByBool_1B511D7041E0C6A313D2F98EEEDF6B94() end
function UAbp_HumanoidCS_Simple4Dir_C:EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_35C984434C1F5F898F593BB514E5956C() end
function UAbp_HumanoidCS_Simple4Dir_C:EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_BlendListByBool_2953EC634E9365C1EBA3618085A896D9() end
function UAbp_HumanoidCS_Simple4Dir_C:EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_1071C6D745E7C01659E7EF980DA34D64() end
function UAbp_HumanoidCS_Simple4Dir_C:EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_9B82B7134310A46AA01B3EB1BD58CF18() end
function UAbp_HumanoidCS_Simple4Dir_C:EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_61B479AA4B4E26AF9E356C9A27DFAF1D() end
function UAbp_HumanoidCS_Simple4Dir_C:EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_SequencePlayer_A87E1822407ECB0E657412AAA73B4BA9() end
function UAbp_HumanoidCS_Simple4Dir_C:EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_BBCC167249B3F206916C6D8749070E0B() end
function UAbp_HumanoidCS_Simple4Dir_C:EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_D102B5B8414212C266469CAD833AACB3() end
function UAbp_HumanoidCS_Simple4Dir_C:EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_F9B8D6D242AEAA75FB435F80A681A584() end
---@param EntryPoint int32
function UAbp_HumanoidCS_Simple4Dir_C:ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir(EntryPoint) end


