---@enum EGSARTERIES_PLACEMENT_LEVEL
EGSARTERIES_PLACEMENT_LEVEL = {
    NONE = 0,
    BUTTOM = 1,
    TOP = 2,
    TOP_OR_BOTTOM = 3,
    ALL = 7,
    EGSARTERIES_PLACEMENT_MAX = 8,
}

---@enum EGSARTERIES_PLACEMENT_STRATEGY
EGSARTERIES_PLACEMENT_STRATEGY = {
    ANY = 0,
    PREFER_STACKABLE = 1,
    BASE = 2,
    EGSARTERIES_PLACEMENT_MAX = 3,
}

---@enum EGSATERIES_PLACEMENT_TYPE
EGSATERIES_PLACEMENT_TYPE = {
    PLACEMENT_CRATE = 0,
    PLACEMENT_MAX = 1,
}

---@enum GSATERIES_SAMPLE_AXIS
GSATERIES_SAMPLE_AXIS = {
    X = 0,
    Y = 1,
    Z = 2,
    GSATERIES_SAMPLE_MAX = 3,
}

---@enum GSATERIES_SIDE_DISTRIBUTION_FEATURE
GSATERIES_SIDE_DISTRIBUTION_FEATURE = {
    CENTER = 0,
    END = 1,
    EVEN = 2,
    GSATERIES_SIDE_DISTRIBUTION_MAX = 3,
}

---@enum GSATERIES_SIDE_SELECT_FEATURE
GSATERIES_SIDE_SELECT_FEATURE = {
    RANDOM_SIDE = 0,
    LONGEST_SIDE = 1,
    SHORTEST_SIDE = 2,
    EACH_SIDE = 3,
    FIRST_SIDE = 4,
    GSATERIES_SIDE_SELECT_MAX = 5,
}

---@enum GSArteriesIteractType
GSArteriesIteractType = {
    Spline = 0,
    Box = 1,
    BoxWithSpline = 2,
    GSArteriesIteractType_MAX = 3,
}

